version: '3'

services:
    rstudio:
        image: ymattu/mecab-d:latest
        container_name: godakr
        hostname: rstu2023
        # privileged: true
        tty: true
        shm_size: '1gb'
        ports:
            - "8787:8787"
        expose:
            - '8787'
        build:
            context: .
        environment:
            - TZ=TZ=Asia/Tokyo
            - DISABLE_AUTH=true
            - PYTHONUSERBASE=/home/rstudio/.pip
        volumes:
            - ./work01:/home/rstudio/work
            - renv:/home/rstudio/.cache/R/renv
            - pip:/home/rstudio/.pip
            - julia:/home/rstudio/.julia
            - TinyTeX:/home/rstudio/.TinyTeX
            - fonts:/usr/share/fonts
volumes:
  renv:
    external: true
  pip:
    external: true
  julia:
    external: true
  TinyTeX:
    external: true
  fonts:
    external: true